### ISSUE TITLE
Add a new component called 'Contributors'

### ISSUE THREAD

**Issue by mattarnster** [mattarnster/reactStartPage3#12]
This new component should pull data from the GitHub API to list the contributors for this project.

This is the source for the data:
https://api.github.com/repos/mattarnster/reactStartPage3/contributors

It should be included on the Settings page in the existing card here underneath the existing contents:
![image](https://user-images.githubusercontent.com/6093927/94939278-e5675e00-049f-11eb-9c04-4b35558ce4b2.png)

The contents of the new component should be the avatar/gravatar of the GitHub user.
 It should be laid out like so:
![image](https://user-images.githubusercontent.com/6093927/94939900-c917f100-04a0-11eb-86e7-f0f363cc0b74.png)

The image should have an alt tag of the username of the user, and should be a link to the user's GitHub profile page.

**Comment by DeadEnglish** [comment]
Hey, would you mind if I took a stab at this?

**Comment by mattarnster** [comment]
You sure can! I shall assign it to you now.

**Comment by abhishekjain35** [comment]
Can I work on this?

**Comment by mattarnster** [comment]
Hi @abhishekjain35, sorry but @DeadEnglish got there first I'm afraid. There is another issue open, however, if you'd like to have a go at it.

**Comment by DeadEnglish** [comment]
hey @mattarnster, The PR should be ready to review now #16

**Comment by mattarnster** [comment]
Thanks for your contribution!

**Comment by mattarnster** [comment]
Hi @DeadEnglish, it looks like it fails the first time. Could you remove the ghContributors localstorage key and re-test to see if you can reproduce the error?
![image](https://user-images.githubusercontent.com/6093927/94949660-4a768000-04af-11eb-86c9-635909095dcd.png)

**Comment by mattarnster** [comment]
I've added a quick fix for this. Thanks again for your contribution!

**Comment by DeadEnglish** [comment]
@mattarnster Sorry for this, I didn't get round to fully testing it. Please see my recent PR #17 where I'm getting and setting the data correctly and not looping through the data if it's not set stopping the initial load issue.

**Comment by mattarnster** [comment]
Thanks again! Have a great day :)
