### ISSUE TITLE
Implement custom background picture functionality

### ISSUE THREAD

**Issue by mattarnster** [mattarnster/reactStartPage3#13]
I'd like for users to be able to add a custom background in, instead of using the default one.

It would need a new component added on the settings page, and the background could be stored in LocalStorage. Either a URL or file for a background image could be used. 

If it's a file, it would need to be converted into base64 and held in LocalStorage, and if it's a URL, the URL would be stored.

When the app is loaded, the background image would need to be retrieved from LocalStorage and then set on the body.

You could implement a modal for the user to select the background image from their PC, or provide a URL.

Documentation for the modal functionality using Materialize.css is available here:
http://archives.materializecss.com/0.100.2/modals.html

**Comment by deepank120896** [comment]
@mattarnster I would like to work on this

**Comment by mattarnster** [comment]
Hi @deepank120896, you're very welcome to work on this. I will assign it to you now.

**Comment by mattarnster** [comment]
Functionality implemented and merged into master.
