### ISSUE TITLE
Add a loading indicator to the Contributors component on the Settings page

### ISSUE THREAD

**Issue by mattarnster** [mattarnster/reactStartPage3#18]
We need to add a loading indicator to the Contributors component whilst it is fetching data.

**Comment by roygrv21** [comment]
Can I take up this task?

**Comment by mattarnster** [comment]
@roygrv21 You sure can! I'll assign it to you now.

**Comment by roygrv21** [comment]
I am getting this error after npm start(I have already done npm install).  Could you please help me with it ?
![Capture](https://user-images.githubusercontent.com/36206378/95114687-efb87f00-0761-11eb-9fde-4b8aab63698a.PNG)

**Comment by mattarnster** [comment]
Hi, that was my bad. I have fixed the incorrect version number. Pull the latest commit and it should be fixed.

**Comment by sureshmangs** [comment]
Working on the issue.

**Comment by mattarnster** [comment]
Thanks @sureshmangs!
