### ISSUE TITLE
Make sure input is not empty before adding new sites

### ISSUE THREAD

**Issue by mattarnster** [mattarnster/reactStartPage3#5]
Currently, users can add empty sites by just clicking the submit button.

We should validate the input before adding the site to make sure both fields are filled.

**Comment by pedrogneri** [comment]
Hi! Can I get this one?

**Comment by mattarnster** [comment]
Hey there @pedrogneri! You sure can!

**Comment by pedrogneri** [comment]
@mattarnster Do you want to provide feedback to the user if he does not fill in the fields and click submit? As an error message, or perhaps leaving the button disabled for example

**Comment by mattarnster** [comment]
I think leaving the button disabled until both fields are filled would be good.

**Comment by pedrogneri** [comment]
Done! #11
