### ISSUE TITLE
Rename Add/Remove button on mobile

### ISSUE THREAD

**Issue by mattarnster** [mattarnster/reactStartPage3#6]
Rename the button in the mobile header from 'Add/Remove' to 'Manage Sites'.

**Comment by DeadEnglish** [comment]
Hey, would you mind if I grabbed this?

**Comment by mattarnster** [comment]
@DeadEnglish Since you're working on the contributors component, I'll give @abhishekjain35 a chance to work on this one first if they would like to.

**Comment by abhishekjain35** [comment]
Yeah, I would like to work on this. Thanks @mattarnster  You're very kind.

**Comment by abhishekjain35** [comment]
I've made the PR. Please review it. @mattarnster

**Comment by mattarnster** [comment]
Merged. Thanks for your help!
